CREATE TABLE DbMiddle (
	ID	INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Gameloop	INTEGER NOT NULL,
	Team	INTEGER NOT NULL,
	ReplayID	INTEGER,
	CONSTRAINT FK_DbMiddle_DSReplays_ReplayID FOREIGN KEY(ReplayID) REFERENCES DSReplays (ID) ON DELETE RESTRICT
);